query_box_2(T):-grammar1("[[\"aa,]\",b,\"c\",[]],1]",T).
grammar1(U,T):-compound(U,"",[],T).
compound213(U,U,T,T).
compound(Vgp1,Vgp2,T,U):-grammar_part("[",Vgp1,Vgp3),grammar_part("]",Vgp3,Vgp4),compound213(Vgp4,Vgp2,T,U).
compound(Vgp1,Vgp2,T,U):-grammar_part("[",Vgp1,Vgp3),compound21(Vgp3,Vgp4,T,V),grammar_part("]",Vgp4,Vgp5),compound213(Vgp5,Vgp2,V,U).
compound212(U,U,T,T).
compound21(Vgp1,Vgp2,T,U):-item(Vgp1,Vgp3,I),lookahead(Vgp3,Vgp4,"]"),wrap(I,Itemname1),append(T,Itemname1,V),compound212(Vgp4,Vgp2,V,U).
compound21(Vgp1,Vgp2,T,U):-item(Vgp1,Vgp3,I),grammar_part(",",Vgp3,Vgp4),compound21(Vgp4,Vgp2,[],Compound1name),wrap(I,Itemname1),append(T,Itemname1,V),append(V,Compound1name,U).
item(Vgp1,Vgp2,T):-grammar_part("\"",Vgp1,Vgp3),word21(Vgp3,Vgp4,"",T),grammar_part("\"",Vgp4,Vgp2).
item(Vgp1,Vgp2,T):-number21(Vgp1,Vgp2,"",U),stringtonumber(U,T).
item(Vgp1,Vgp2,T):-word21_atom(Vgp1,Vgp2,"",T1),atom_string(T,T1).
item(Vgp1,Vgp2,T):-compound(Vgp1,Vgp2,[],T).
number212(U,U,T,T).
number21(Vgp1,Vgp2,T,U):-grammar_part(A,Vgp1,Vgp3),commaorrightbracketnext(Vgp3,Vgp4),((stringtonumber(A,A1),number(A1))->(true);((equals4(A,".")->(true);(equals4(A,"-"))))),stringconcat(T,A,V),number212(Vgp4,Vgp2,V,U).
number21(Vgp1,Vgp2,T,U):-grammar_part(A,Vgp1,Vgp3),((stringtonumber(A,A1),number(A1))->(true);((equals4(A,".")->(true);(equals4(A,"-"))))),stringconcat(T,A,V),number21(Vgp3,Vgp2,"",Numberstring),stringconcat(V,Numberstring,U).
word212(U,U,T,T).
word21(Vgp1,Vgp2,T,U):-grammar_part(A,Vgp1,Vgp3),quote_next(Vgp3,Vgp4),not((=(A,"\""))),stringconcat(T,A,V),word212(Vgp4,Vgp2,V,U).
word21(Vgp1,Vgp2,T,U):-grammar_part(A,Vgp1,Vgp3),not((=(A,"\""))),stringconcat(T,A,V),word21(Vgp3,Vgp2,"",Wordstring),stringconcat(V,Wordstring,U).
word212_atom(U,U,T,T).
word21_atom(Vgp1,Vgp2,T,U):-%writeln1(word21_atom(Vgp1,Vgp2,T,U)),trace,
grammar_part(A,Vgp1,Vgp3),commaorrightbracketnext(Vgp3,Vgp4),not((=(A,"\""))),not((=(A,"["))),not((=(A,"]"))),stringconcat(T,A,V),word212_atom(Vgp4,Vgp2,V,U).
word21_atom(Vgp1,Vgp2,T,U):-grammar_part(A,Vgp1,Vgp3),not((=(A,"\""))),not((=(A,"["))),not((=(A,"]"))),stringconcat(T,A,V),word21_atom(Vgp3,Vgp2,"",Wordstring),stringconcat(V,Wordstring,U).
commaorrightbracketnext(Vgp1,Vgp2):-lookahead(Vgp1,Vgp2,",").
commaorrightbracketnext(Vgp1,Vgp2):-lookahead(Vgp1,Vgp2,"]").
quote_next(Vgp1,Vgp2):-lookahead(Vgp1,Vgp2,"\"").
lookahead(A,A,B):-stringconcat(B,D,A).

grammar_part(A,B,C):-string_concat(A,C,B),string_length(A,1).
stringconcat(A,B,C):-string_concat(A,B,C).
stringtonumber(A,B):-number_string(B,A).
equals4(A,B):-A=B.
wrap(A,B):-B=[A].
