% Generated by Prolog to Starlog Converter
% Date/Time: 2025-07-02 00:25:18 UTC
% User: luciangreenPlease
% Compression applied where possible

hi(A,B,C,D,E):-F is ("Hi, ":A),G is (F:", are you getting ready for "),H is (G:B),I is (H:C),J is (I:D),K is (J:"="),[C,B,D]..=L,number_to_string(L,M),N is (K:M),E is (N:".").
