% Generated by Starlog to Prolog Converter
% Date/Time: 2025-07-02 00:25:18 UTC
% User: luciangreenPlease
% Decompression applied where possible

:-include('../../listprologinterpreter/listprolog.pl').
hi(A,B,C,D,E):-string_concat("Hi, ",A,B1),string_concat(B1,", are you getting ready for ",C1),string_concat(C1,B,D1),string_concat(D1,C,E1),string_concat(E1,D,F1),string_concat(F1,"=",G1),[C,B,D]..=H1,number_to_string(H1,I1),string_concat(G1,I1,J1),string_concat(J1,".",E).
