% ["Fundamentals of Pedagogy and Pedagogy Indicators","FUNDAMENTALS OF PEDAGOGY by Lucian Green *Two Uses* 1 of 30.txt",0,algorithms,"[""Green, L 2021, <i>Two Uses 1 of 30</i>, Lucian Academy Press, Melbourne."",""Green, L 2021"",1,""FUNDAMENTALS OF PEDAGOGY"]

br_details :-
	writeln("What is the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What are two uses (in verb(object) form) for the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What are two types (in verb(object) form) in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is an object (in verb(object) form) for the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is a touching relationship (in verb(object) form) in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is a human judgement (in verb(object) form) for a noun in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is a human judgement (in verb(object) form) for a verb in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is a room (in verb(object) form) in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is a part of a room (in verb(object) form) in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is a direction an object faces (in verb(object) form) in the sentence?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is an object required before the sentence (in verb(object) form)?"),
	read_string(user_input,"\n","\r",_,_),
	writeln("What is an object required after the sentence (in verb(object) form)?"),
	read_string(user_input,"\n","\r",_,_).
